version: "3"
services:
  v2ray-onekeyscript:
    build:
      context: .
      args:
        PROTOCOL: ${PROTOCOL}
        PORT: ${PORT}
        ADBLOCK: ${ADBLOCK}
    # volumes:
    # - ./config.json:/etc/v2ray/config.json:rw
    # - ./233blog_v2ray_backup.conf:/etc/v2ray/233blog_v2ray_backup.conf:rw
    # restart: always
    networks: 
      - v2ray
    ports:
      - "${PORT}:${PORT}"
      - "${PORT}:${PORT}/udp"

networks: 
  v2ray: